tests/control.in: uicheck-sw requires impress
ERROR: test_tdf150151 (tdf150151.Tdf150151)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.HSkmsB/build.mJH/src/sw/qa/uitest/writer_tests5/tdf150151.py", line 30, in test_tdf150151
    with self.ui_test.load_empty_file("impress") as document:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/tmp/autopkgtest.HSkmsB/build.mJH/src/uitest/uitest/test.py", line 111, in load_empty_file
    yield self.load_component_from_url("private:factory/s" + app, "OnNew")
  File "/tmp/autopkgtest.HSkmsB/build.mJH/src/uitest/uitest/test.py", line 90, in load_component_from_url
    component =  self.get_desktop().loadComponentFromURL(url, "_default", 0, tuple())
uitest.test.com.sun.star.lang.IllegalArgumentException: Unsupported URL <private:factory/simpress>: "type detection failed" at ./framework/source/loadenv/loadenv.cxx:189

https://gerrit.libreoffice.org/c/core/+/138295